# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/app
#     environment:
#       FLASK_DEBUG: 1
#       FLASK_APP: run.py
#       FLASK_ENV: development
#       PYTHONWARNINGS: "ignore::DeprecationWarning"
#     command: poetry run flask run --host=0.0.0.0

#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: stonks
#       POSTGRES_PASSWORD: Cybertron_2541
#       POSTGRES_DB: stonks
  
#   adminer:
#     image: adminer
#     ports:
#       - "8080:8080"


version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_db_ui
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
