STOCKS_DATA = {
    "all_stocks": {
        "AAPL": {"name": "Apple", "symbol": "AAPL"},
        "MSFT": {"name": "Microsoft", "symbol": "MSFT"},
        "GOOGL": {"name": "Alphabet", "symbol": "GOOGL"},
        "AMZN": {"name": "Amazon", "symbol": "AMZN"},
        "META": {"name": "Meta", "symbol": "META"},
        "TSLA": {"name": "Tesla", "symbol": "TSLA"},
        "NVDA": {"name": "Nvidia", "symbol": "NVDA"},
        "NFLX": {"name": "Netflix", "symbol": "NFLX"},
        "BRK.B": {"name": "Berkshire Hathaway", "symbol": "BRK.B"},
        "V": {"name": "Visa", "symbol": "V"},
        "JNJ": {"name": "Johnson & Johnson", "symbol": "JNJ"},
        "WMT": {"name": "Walmart", "symbol": "WMT"},
        "JPM": {"name": "JPMorgan Chase", "symbol": "JPM"},
        "PG": {"name": "Procter & Gamble", "symbol": "PG"},
        "UNH": {"name": "UnitedHealth", "symbol": "UNH"},
        "DIS": {"name": "Disney", "symbol": "DIS"},
        "HD": {"name": "Home Depot", "symbol": "HD"},
        "MA": {"name": "Mastercard", "symbol": "MA"},
        "PYPL": {"name": "PayPal", "symbol": "PYPL"},
        "XOM": {"name": "ExxonMobil", "symbol": "XOM"},
        "BAC": {"name": "Bank of America", "symbol": "BAC"},
        "KO": {"name": "Coca-Cola", "symbol": "KO"},
        "PFE": {"name": "Pfizer", "symbol": "PFE"},
        "PEP": {"name": "PepsiCo", "symbol": "PEP"},
        "ABBV": {"name": "AbbVie", "symbol": "ABBV"},
        "COST": {"name": "Costco", "symbol": "COST"},
        "T": {"name": "AT&T", "symbol": "T"},
        "CVX": {"name": "Chevron", "symbol": "CVX"},
        "ABT": {"name": "Abbott Laboratories", "symbol": "ABT"},
        "CRM": {"name": "Salesforce", "symbol": "CRM"},
        "CMCSA": {"name": "Comcast", "symbol": "CMCSA"},
        "INTC": {"name": "Intel", "symbol": "INTC"},
        "ADBE": {"name": "Adobe", "symbol": "ADBE"},
        "CSCO": {"name": "Cisco Systems", "symbol": "CSCO"},
        "NKE": {"name": "Nike", "symbol": "NKE"},
        "MCD": {"name": "McDonald's", "symbol": "MCD"},
        "MDT": {"name": "Medtronic", "symbol": "MDT"},
        "TXN": {"name": "Texas Instruments", "symbol": "TXN"},
        "QCOM": {"name": "Qualcomm", "symbol": "QCOM"},
        "HON": {"name": "Honeywell", "symbol": "HON"},
        "LLY": {"name": "Eli Lilly", "symbol": "LLY"},
        "ORCL": {"name": "Oracle", "symbol": "ORCL"},
        "GILD": {"name": "Gilead Sciences", "symbol": "GILD"},
        "AMGN": {"name": "Amgen", "symbol": "AMGN"},
        "BMY": {"name": "Bristol-Myers Squibb", "symbol": "BMY"},
        "GE": {"name": "General Electric", "symbol": "GE"},
        "SBUX": {"name": "Starbucks", "symbol": "SBUX"},
        "DHR": {"name": "Danaher", "symbol": "DHR"},
        "UPS": {"name": "United Parcel Service", "symbol": "UPS"},
        "LIN": {"name": "Linde", "symbol": "LIN"},
        "SPGI": {"name": "S&P Global", "symbol": "SPGI"},
        "BLK": {"name": "BlackRock", "symbol": "BLK"}
    }
}