"""Remove unique constraint from symbol column

Revision ID: 2dab7384d15c
Revises: be97fad57d0a
Create Date: 2025-01-28 10:10:41.813496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dab7384d15c'
down_revision = 'be97fad57d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint('stock_symbol_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_unique_constraint('stock_symbol_key', ['symbol'])

    # ### end Alembic commands ###
