"""Added is_global column to Stock model

Revision ID: 412ba10f2f93
Revises: 2dab7384d15c
Create Date: 2025-01-28 16:15:20.762003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412ba10f2f93'
down_revision = '2dab7384d15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('is_global')

    # ### end Alembic commands ###
