"""Added reset token fields

Revision ID: 743b8f56708f
Revises: e901e901ebaf
Create Date: 2025-02-07 15:32:59.036005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743b8f56708f'
down_revision = 'e901e901ebaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
